
a = int(input())
b = int(input())
print("a = " + str(a))
print("b = " + str(b))
print("a + b = " + str(a+b))
print("a - b = " + str(a-b))
print("a * b = " + str(a*b))
print("a ** b = " + str(a**b))
print("a // b = " + str(a//b))
print("a % b = " + str(a%b))